# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pincodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=60)),
                ('alternate_number', models.CharField(blank=True, max_length=15)),
                ('company_logo', models.URLField(blank=True)),
                ('year_established', models.DateField(blank=True, null=True)),
                ('company_website', models.URLField(blank=True)),
                ('email_verification', models.BooleanField(default=0)),
                ('mobile_verification', models.BooleanField(default=0)),
                ('account_active', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_line_1', models.CharField(blank=True, max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('landmark', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('name_on_pan', models.CharField(blank=True, max_length=100)),
                ('dob_on_pan', models.DateField(blank=True, null=True)),
                ('pan_scanned_copy', models.FileField(blank=True, max_length=200, upload_to=None)),
                ('tin', models.CharField(blank=True, max_length=11)),
                ('tin_scanned_copy', models.FileField(blank=True, max_length=200, upload_to=None)),
                ('pan_verification', models.BooleanField(default=0)),
                ('tin_verification', models.BooleanField(default=0)),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pincodes.Pincode')),
            ],
        ),
        migrations.CreateModel(
            name='DistributorBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holders_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=18)),
                ('ifsc', models.CharField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('mobile_number', models.CharField(max_length=13, unique=True)),
                ('profile_picture', models.ImageField(blank=True, max_length=200, upload_to=None)),
                ('address_line_1', models.CharField(blank=True, max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('landmark', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('account_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributors', models.ManyToManyField(to='users.Distributor')),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pincodes.Pincode')),
            ],
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('mobile_number', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('profile_picture', models.ImageField(blank=True, max_length=200, upload_to=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Distributor')),
            ],
        ),
    ]
